### ISSUE TITLE
How does SOT compare to UMAP?

### ISSUE THREAD

**Issue by JustinMBrown** [DanielShalam/SOT#2]
UMAP is also a non-parametric transformation function that works on embeddings, and the section on graph nature of SOT reminded me of UMAP. It's main purpose is dimensionality reduction, which y'all say y'all are going to explore in future work.

UMAP is based on geometric algebra and surfaces, so I'm wondering if there's any mathematical connection between the two. Disclaimer: I only have a surface level understanding of both SOT and UMAP lol

**Comment by DanielShalam** [comment]
I'm not too familiar with UMAP but I think that the SOT can replace the fuzzy topological graph created in UMAP.
Actually, it can be very interesting to try it.
