### ISSUE TITLE
Suggested fix for batched mode in SOT

### ISSUE THREAD

**Issue by tomkark** [DanielShalam/SOT#3]
https://github.com/DanielShalam/SOT/blob/6978057cc018a342a4706a89b92d735fc78027fb/self_optimal_transport.py#L67

Should be changed to:
```python
features = features / max_probability[:, None, None]
```

To avoid crashing of mismatch in dimension.

**Comment by DanielShalam** [comment]
Hi, thanks.
I modified it slightly different to allow non-batched mode.
