### ISSUE TITLE
Complete repo (with train & test codes available)

### ISSUE THREAD

**Issue by briliantnugraha** [DanielShalam/SOT#4]
Hi, thanks for the nice repo on few shot classification.

Could I know, when will the complete code be available?

I've seen that you've already put SOT code here, is it PnP to with Protonet-style/PTMAP-SF models? (resnet12/w-resnet28)

Looking forward to your reply. TIA~

**Comment by DanielShalam** [comment]
Hi ! Thank you for your interest.

The complete code will be available in the next few weeks, with additional use-cases as well.

For the current code of the SOT, it is PnP with the methods we used. 
You just need to replace the original features with their SOT and it should be fine.

Hope it answers your questions.

**Comment by briliantnugraha** [comment]
I see, got it, thanks for the fast response!
