### ISSUE TITLE
How to setup relevant datasets for training and evaluation?

### ISSUE THREAD

**Issue by kshitijd20** [DanielShalam/SOT#7]
I would like to run the tranining on miniImagenet / CIFAR-FS but the instructions on where to download it from or how to prepare the datasets is not clear. Can you please update the instructions on how to download and prepare datasets for training and evaluation?

**Comment by DanielShalam** [comment]
Hi !
Sure, I will update the code to make it more clear

**Comment by DanielShalam** [comment]
You can find instructions under /SOT/datasets/.
Closing the issue for now.
