### ISSUE TITLE
can you share your test/inference code?

### ISSUE THREAD

**Issue by Realdr4g0n** [DanielShalam/SOT#8]
Thank you for sharing the results.
Aren't you going to provide inference code separately other than evaluation?
If you use the sampler as is, data that is not inferred will occur. Is there another way?

**Comment by DanielShalam** [comment]
Hi, Sorry but I didn't fully understand you question.
However, by setting --evaluate true in the train.py script it will sample from the test set.
Is that somehow answer your question ?
